"""
Default ad slots matching quizwinz.com structure exactly
"""

QUIZWINZ_AD_SLOTS = [
    {
        "id": "header-banner",
        "name": "Header Banner",
        "ad_unit_id": "",
        "ad_code": "",
        "placement": "header",
        "ad_type": "adsense",
        "is_active": False,
        "description": "Top of the page banner advertisement",
    },
    {
        "id": "sidebar-right",
        "name": "Sidebar Right",
        "ad_unit_id": "",
        "ad_code": "",
        "placement": "sidebar",
        "ad_type": "adsense",
        "is_active": False,
        "description": "Right side of the page advertisement",
    },
    {
        "id": "between-questions-1",
        "name": "Between Questions #1",
        "ad_unit_id": "",
        "ad_code": "",
        "placement": "between-questions",
        "ad_type": "adsense",
        "is_active": False,
        "description": "Advertisement between quiz questions (position 1)",
    },
    {
        "id": "between-questions-2",
        "name": "Between Questions #2",
        "ad_unit_id": "",
        "ad_code": "",
        "placement": "between-questions",
        "ad_type": "adsense",
        "is_active": False,
        "description": "Advertisement between quiz questions (position 2)",
    },
    {
        "id": "between-questions-3",
        "name": "Between Questions #3",
        "ad_unit_id": "",
        "ad_code": "",
        "placement": "between-questions",
        "ad_type": "adsense",
        "is_active": False,
        "description": "Advertisement between quiz questions (position 3)",
    },
    {
        "id": "footer-banner",
        "name": "Footer Banner",
        "ad_unit_id": "",
        "ad_code": "",
        "placement": "footer",
        "ad_type": "adsense",
        "is_active": False,
        "description": "Bottom of the page banner advertisement",
    },
    {
        "id": "popup-interstitial",
        "name": "Popup Interstitial",
        "ad_unit_id": "",
        "ad_code": "",
        "placement": "popup",
        "ad_type": "adsense",
        "is_active": False,
        "description": "In-game popup advertisement",
    },
    {
        "id": "quiz-result-banner",
        "name": "Quiz Result Banner",
        "ad_unit_id": "",
        "ad_code": "",
        "placement": "quiz-result",
        "ad_type": "adsense",
        "is_active": False,
        "description": "Advertisement after quiz completion",
    },
    {
        "id": "category-page-top",
        "name": "Category Page Top",
        "ad_unit_id": "",
        "ad_code": "",
        "placement": "category-top",
        "ad_type": "adsense",
        "is_active": False,
        "description": "Top of quiz category selection page",
    },
    {
        "id": "category-page-bottom",
        "name": "Category Page Bottom",
        "ad_unit_id": "",
        "ad_code": "",
        "placement": "category-bottom",
        "ad_type": "adsense",
        "is_active": False,
        "description": "Bottom of quiz category selection page",
    },
]
